// Gameplay balance constants for bullet-hell.ts
// Every number that affects difficulty, economy, or game feel lives here.
// Visual/rendering values (shadow blur, particle colors, font sizes) stay inline.

export const BAL = {
  player: {
    w: 20,
    h: 24,
    hp: 5,
    maxHp: 5,
    speed: 320,
    shootCooldown: 0.12,
    maxBullets: 3,
    bulletSpeed: 600,
    bulletW: 4,
    bulletH: 12,
    invincibleMs: 1500,
    grazeDistance: 30,
    grazeScore: 5,
  },

  wave: {
    baseEnemies: 4,
    enemiesPerWave: 1,
    baseSpawnInterval: 1.5,
    spawnIntervalDecay: 0.05,
    minSpawnInterval: 0.4,
    shootStartWave: 3,
    shootChanceBase: 0.2,
    shootChancePerWave: 0.03,
    shootChanceMax: 0.85,
    shootTimerBase: 1.5,
    shootTimerRandom: 2,
    shootIntervalBase: 3.5,
    shootIntervalDecay: 0.08,
    minShootInterval: 1.5,
    introDuration: 2,
    bossIntroDuration: 3,
    bossWaveInterval: 10,
    hpBonusDivisor: 3,
    speedBonusPerWave: 2,
  },

  enemyTiers: {
    short: { maxLength: 4, hp: 1, speed: 100, speedRandom: 40 },
    medium: { maxLength: 8, hp: 2, speed: 70, speedRandom: 30 },
    long: { hp: 3, speed: 50, speedRandom: 20 },
  },

  boss: {
    hpBase: 20,
    hpPerWave: 3,
    speed: 40,
    restY: 80,
    sineSpeed: 0.8,
    sineAmplitudeRatio: 0.3,
    shootInterval: 1.2,
    attackTimer: 2.0,
    killSlowMo: 0.15,
    killSlowMoDuration: 1.5,
    killShakeIntensity: 12,
    killShakeDuration: 0.6,
    killPoints: 10,
  },

  enemyTypes: {
    normal: { unlockWave: 1, weight: 3 },
    splitter: {
      unlockWave: 5,
      weight: 1,
      hpBonus: 1,
      childCountBase: 2,
      childCountRandom: 2,
      childOffsetX: 30,
      childSpeedMult: 1.5,
    },
    swarm: {
      unlockWave: 8,
      weight: 1,
      countBase: 8,
      countRandom: 3,
      clusterSpread: 80,
      speedBase: 150,
      speedPerWave: 6,
      speedRandom: 60,
    },
    cloaker: {
      unlockWave: 11,
      weight: 1,
      cloakSpeed: 1.5,
      visibleThreshold: -0.3,
    },
  },

  movement: {
    sine: { frequency: 2, amplitude: 80 },
    zigzag: { frequency: 2, amplitude: 60 },
    erratic: { freq1: 6, amp1: 40, freq2: 4.3, amp2: 25 },
  },

  enhancements: {
    homing: {
      baseChance: 0.15,
      chancePerLevel: 0.10,
      speed: 500,
      turnRate: 8,
      bulletW: 5,
      bulletH: 10,
      lifetime: 2.5,
    },
    exploding: {
      baseChance: 0.15,
      chancePerLevel: 0.10,
      aoeRadius: 80,
    },
    radial: {
      baseChance: 0.15,
      chancePerLevel: 0.10,
      centerSpeed: 600,
      sideSpeed: 550,
      spreadAngle: Math.PI / 4,
    },
    orbital: {
      baseChance: 0.15,
      chancePerLevel: 0.10,
      radius: 180,
      angularVelocity: 14,
      baseRotations: 5,
      rotationsPerLevel: 1,
    },
    chainLightning: {
      baseChance: 0.15,
      chancePerLevel: 0.10,
      baseRange: 120,
      rangePerLevel: 20,
      baseChains: 1,
      chainsEveryNLevels: 2,
      boltLife: 0.4,
      jitter: 30,
    },
    golden: {
      baseChance: 0.05,
      chancePerLevel: 0.05,
      pointMult: 5,
      gildedDuration: 3,
    },
    gravityWell: {
      baseChance: 0.15,
      chancePerLevel: 0.10,
      speed: 120,
      baseLife: 2,
      lifePerLevel: 0.5,
      drag: 2,
      basePullRadius: 100,
      pullRadiusPerLevel: 20,
      basePullForce: 80,
      pullForcePerLevel: 15,
      pullForceCap: 1.2,
    },
    lifeDrain: {
      baseChance: 0.15,
      chancePerLevel: 0.10,
      baseHealChance: 0.12,
      healChancePerLevel: 0.06,
      doubleHealLevel: 3,
      doubleHealChance: 0.15,
    },
    pierce: {
      baseChance: 0.15,
      chancePerLevel: 0.10,
      basePierceCount: 1,
      bulletH: 14,
    },
  },

  attacks: {
    aimed: {
      unlockWave: 1,
      baseSpeed: 180,
      speedPerWave: 5,
    },
    aimedBurst: {
      baseSpeed: 200,
      speedPerWave: 5,
      count: 5,
      spreadAngle: 0.15,
    },
    radial: {
      unlockWave: 6,
      baseCount: 8,
      countPerWaveDivisor: 3,
      baseSpeed: 140,
      speedPerWave: 3,
    },
    laser: {
      unlockWave: 9,
      warningDuration: 0.8,
      beamLife: 0.35,
      beamWidth: 14,
      bossOffsets: [-100, 100] as readonly number[],
    },
    mine: {
      unlockWave: 12,
      baseSpeed: 250,
      speedRandom: 100,
      bossSpeed: 400,
      bossSpeedRandom: 150,
      targetSpreadX: 80,
      targetSpreadY: 60,
      bossFullCanvas: true,
      drag: 3,
      fuseBase: 2.5,
      fuseRandom: 1.5,
      blastRadius: 120,
      bossVolley: 4,
    },
    spiral: {
      baseSpeed: 120,
      speedPerWave: 2,
      volleys: 5,
      volleyAngleStep: 0.4,
      armsPerVolley: 3,
      angleIncrement: 2.0,
    },
    wall: {
      gapMinRatio: 0.15,
      gapRangeRatio: 0.7,
      gapWidth: 110,
      baseSpeed: 130,
      speedPerWave: 3,
      spacing: 30,
      bulletW: 20,
      bulletH: 8,
    },
    shotgun: {
      unlockWave: 6,
      count: 5,
      spread: Math.PI / 3,
      baseSpeed: 220,
      speedPerWave: 4,
    },
    shotgunBoss: {
      count: 9,
      spread: Math.PI / 4,
      baseSpeed: 260,
      speedPerWave: 4,
    },
  },

  loot: {
    dropChance: 0.08,
    bossDropChance: 0.5,
    crateSpeed: 30,
    cratePickupRadius: 60,
    fullSlotsBonus: 5,
    rerollBaseCost: 3,
    rerollCostPerWaveDivisor: 2,
  },

  shop: {
    hpUpBase: 3,
    healBase: 2,
    fireRateBase: 3,
    fireRateMin: 0.04,
    fireRateStep: 0.02,
    maxBulletsBase: 2,
    maxBulletsCap: 12,
    enhanceLevelCap: 7,
    enhanceBaseCost: 4,
    sacrificeBaseReward: 3,
    sacrificeRewardPerLevel: 2,
    inflationDivisor: 2,
  },

  bossTypes: {
    classic: { unlockWave: 10 },
    paragraph: {
      unlockWave: 20,
      segmentHpBase: 8,
      segmentHpPerWave: 2,
      segmentSpacing: 8,
      rowSpacing: 30,
      maxWords: 12,
      phaseThresholds: [0.66, 0.33] as readonly number[],
      speedBoostPerPhase: 0.3,
    },
    echo: {
      unlockWave: 30,
      hpBase: 40,
      hpPerWave: 6,
      replayDelay: 5,
      replayBufferSize: 300,
      moveSpeed: 280,
      recordShootInterval: 1.2,
      replayShootInterval: 0.08,
      replayAlwaysFire: true,
    },
    cursor: {
      unlockWave: 40,
      hpBase: 35,
      hpPerWave: 5,
      teleportInterval: 3,
      teleportWarningDuration: 0.5,
      shockwaveRadius: 150,
      shockwaveBullets: 16,
      idleShootInterval: 1.2,
    },
  },

  timing: {
    comboDecay: 3,
    hitFlashRate: 5,
    killScorePerChar: 10,
    killPoints: 1,
    mineStopThreshold: 10,
    mineDrag: 3,
  },

  combo: {
    threshold: 3,
    multPerKill: 0.1,
    maxMultiplier: 5,
  },

  elite: {
    unlockWave: 7,
    chance: 0.08,
    chancePerWave: 0.005,
    maxChance: 0.20,
    hpMultiplier: 2,
    pointMultiplier: 3,
    regenerating: { hpPerSecond: 0.5, unlockWave: 7 },
    bulletSponge: { damageReduction: 0.5, unlockWave: 12 },
    vengeful: { burstCount: 8, burstSpeed: 200, unlockWave: 15 },
  },

  synergies: {
    homingChainLightning: { autoTargetRange: 180, damageBonus: 0.5 },
    explodingRadial: { clusterCount: 4, clusterRadius: 40, clusterSpread: 60 },
    pierceGravityWell: { pullMultiplier: 1.5 },
    goldenLifeDrain: { healOnKill: 2 },
  },

  challenge: {
    startWave: 5,
    chance: 0.15,
    bonusPointMultiplier: 1.5,
    noShoot: { duration: 5 },
    darkness: { lightRadius: 160 },
    speedUp: { enemySpeedMult: 1.8 },
    fragile: { playerHp: 2 },
    bulletHell: { shootChanceMult: 2, shootIntervalMult: 0.5 },
  },
} as const;
