// Gameplay balance constants for bullet-hell.ts
// Every number that affects difficulty, economy, or game feel lives here.
// Visual/rendering values (shadow blur, particle colors, font sizes) stay inline.

export const BAL = {
  player: {
    w: 20,
    h: 24,
    hp: 5,
    maxHp: 5,
    speed: 320,
    shootCooldown: 0.12,
    maxBullets: 3,
    bulletSpeed: 600,
    bulletW: 4,
    bulletH: 12,
    invincibleMs: 1500,
    grazeDistance: 30,
    grazeScore: 5,
  },

  wave: {
    baseEnemies: 6,
    enemiesPerWave: 2,
    baseSpawnInterval: 1.2,
    spawnIntervalDecay: 0.08,
    minSpawnInterval: 0.3,
    shootStartWave: 3,
    shootChanceBase: 0.3,
    shootChancePerWave: 0.05,
    shootChanceMax: 0.9,
    shootTimerBase: 1,
    shootTimerRandom: 2,
    shootIntervalBase: 3,
    shootIntervalDecay: 0.1,
    minShootInterval: 1.5,
    introDuration: 2,
    bossIntroDuration: 3,
    bossWaveInterval: 10,
    hpBonusDivisor: 2,
    speedBonusPerWave: 4,
  },

  enemyTiers: {
    short: { maxLength: 4, hp: 1, speed: 100, speedRandom: 40 },
    medium: { maxLength: 8, hp: 2, speed: 70, speedRandom: 30 },
    long: { hp: 3, speed: 50, speedRandom: 20 },
  },

  boss: {
    hpBase: 30,
    hpPerWave: 5,
    speed: 40,
    restY: 80,
    sineSpeed: 0.8,
    sineAmplitudeRatio: 0.3,
    shootInterval: 0.8,
    attackTimer: 1.5,
    killSlowMo: 0.15,
    killSlowMoDuration: 1.5,
    killShakeIntensity: 12,
    killShakeDuration: 0.6,
    killPoints: 10,
  },

  enemyTypes: {
    normal: { unlockWave: 1, weight: 3 },
    splitter: {
      unlockWave: 5,
      weight: 1,
      hpBonus: 1,
      childCountBase: 2,
      childCountRandom: 2,
      childOffsetX: 30,
      childSpeedMult: 1.5,
    },
    swarm: {
      unlockWave: 8,
      weight: 1,
      countBase: 8,
      countRandom: 3,
      clusterSpread: 80,
      speedBase: 150,
      speedPerWave: 6,
      speedRandom: 60,
    },
    cloaker: {
      unlockWave: 11,
      weight: 1,
      cloakSpeed: 1.5,
      visibleThreshold: -0.3,
    },
  },

  movement: {
    sine: { frequency: 2, amplitude: 80 },
    zigzag: { frequency: 2, amplitude: 60 },
    erratic: { freq1: 6, amp1: 40, freq2: 4.3, amp2: 25 },
  },

  enhancements: {
    homing: {
      baseChance: 0.15,
      chancePerLevel: 0.10,
      speed: 500,
      turnRate: 8,
      bulletW: 5,
      bulletH: 10,
    },
    exploding: {
      baseChance: 0.15,
      chancePerLevel: 0.10,
      aoeRadius: 80,
    },
    radial: {
      baseChance: 0.15,
      chancePerLevel: 0.10,
      centerSpeed: 600,
      sideSpeed: 550,
      spreadAngle: Math.PI / 4,
    },
    orbital: {
      baseChance: 0.15,
      chancePerLevel: 0.10,
      radius: 60,
      angularVelocity: 4,
      baseRotations: 2,
      rotationsPerLevel: 0.5,
    },
    chainLightning: {
      baseChance: 0.15,
      chancePerLevel: 0.10,
      baseRange: 120,
      rangePerLevel: 20,
      baseChains: 1,
      chainsEveryNLevels: 2,
      boltLife: 0.4,
      jitter: 30,
    },
    golden: {
      baseChance: 0.05,
      chancePerLevel: 0.05,
      pointMult: 5,
      gildedDuration: 3,
    },
    gravityWell: {
      baseChance: 0.15,
      chancePerLevel: 0.10,
      speed: 120,
      baseLife: 2,
      lifePerLevel: 0.5,
      drag: 2,
      basePullRadius: 100,
      pullRadiusPerLevel: 20,
      basePullForce: 80,
      pullForcePerLevel: 15,
      pullForceCap: 1.2,
    },
    lifeDrain: {
      baseChance: 0.15,
      chancePerLevel: 0.10,
      baseHealChance: 0.25,
      healChancePerLevel: 0.1,
      doubleHealLevel: 3,
      doubleHealChance: 0.3,
    },
    pierce: {
      baseChance: 0.15,
      chancePerLevel: 0.10,
      basePierceCount: 1,
      bulletH: 14,
    },
  },

  attacks: {
    aimed: {
      unlockWave: 1,
      baseSpeed: 180,
      speedPerWave: 5,
    },
    aimedBurst: {
      baseSpeed: 200,
      speedPerWave: 5,
      count: 5,
      spreadAngle: 0.15,
    },
    radial: {
      unlockWave: 6,
      baseCount: 8,
      countPerWaveDivisor: 3,
      baseSpeed: 140,
      speedPerWave: 3,
    },
    laser: {
      unlockWave: 9,
      warningDuration: 0.8,
      beamLife: 0.35,
      beamWidth: 14,
      bossOffsets: [-100, 100] as readonly number[],
    },
    mine: {
      unlockWave: 12,
      baseSpeed: 250,
      speedRandom: 100,
      bossSpeed: 400,
      bossSpeedRandom: 150,
      targetSpreadX: 80,
      targetSpreadY: 60,
      drag: 3,
      fuseBase: 2.5,
      fuseRandom: 1.5,
      blastRadius: 120,
      bossVolley: 4,
    },
    spiral: {
      baseSpeed: 120,
      speedPerWave: 2,
      volleys: 5,
      volleyAngleStep: 0.4,
      armsPerVolley: 3,
      angleIncrement: 2.0,
    },
    wall: {
      gapMinRatio: 0.15,
      gapRangeRatio: 0.7,
      gapWidth: 70,
      baseSpeed: 150,
      speedPerWave: 3,
      spacing: 30,
      bulletW: 20,
      bulletH: 8,
    },
    shotgun: {
      unlockWave: 6,
      count: 5,
      spread: Math.PI / 3,
      baseSpeed: 220,
      speedPerWave: 4,
    },
    shotgunBoss: {
      count: 9,
      spread: Math.PI / 4,
      baseSpeed: 260,
      speedPerWave: 4,
    },
  },

  loot: {
    dropChance: 0.12,
    bossDropChance: 0.5,
    crateSpeed: 30,
    cratePickupRadius: 60,
    fullSlotsBonus: 5,
    rerollBaseCost: 3,
    rerollCostPerWaveDivisor: 2,
  },

  shop: {
    hpUpBase: 3,
    healBase: 2,
    fireRateBase: 3,
    fireRateMin: 0.04,
    fireRateStep: 0.02,
    maxBulletsBase: 2,
    maxBulletsCap: 12,
    enhanceLevelCap: 5,
    enhanceBaseCost: 3,
    sacrificeBaseReward: 3,
    sacrificeRewardPerLevel: 2,
    inflationDivisor: 3,
  },

  timing: {
    comboDecay: 3,
    hitFlashRate: 5,
    killScorePerChar: 10,
    killPoints: 1,
    mineStopThreshold: 10,
    mineDrag: 3,
  },
} as const;
